alter table notifications drop constraint if exists notifications_type_check;

alter table notifications add constraint notifications_type_check check (type in (
    'API_KEY_CREATED', 'API_KEY_ROTATED', 'API_KEY_REVOKED', 'CREDENTIAL_EXPIRING',
    'WEBHOOK_ENDPOINT_FAILING', 'WEBHOOK_REPEATED_DELIVERY_FAILURE',
    'WEBHOOK_ENDPOINT_DISABLED',
    'QUOTA_WARNING', 'QUOTA_EXCEEDED', 'TRAFFIC_SPIKE',
    'PRODUCTION_REQUEST_RECEIVED', 'PRODUCTION_REVIEW_STARTED',
    'PRODUCTION_APPROVED', 'PRODUCTION_REJECTED', 'PRODUCTION_ACTIVATED',
    'PRODUCTION_REACTIVATED', 'PRODUCTION_SUSPENDED', 'PRODUCTION_REVOKED',
    'SUSPICIOUS_ACTIVITY', 'CREDENTIAL_COMPROMISE', 'SESSION_REVOCATION'
));
