insert into event_types (name, namespace, entity, action, description, category,
                         version, schema, lifecycle)
values
    ('developer.production_access.requested', 'developer', 'production_access', 'requested',
     'A production access request was submitted.', 'SECURITY', 1,
     '{"type":"object","required":["id","status","environmentId"]}', 'ACTIVE'),
    ('developer.production_access.reviewed', 'developer', 'production_access', 'reviewed',
     'A production access request entered review.', 'SECURITY', 1,
     '{"type":"object","required":["id","status","environmentId"]}', 'ACTIVE'),
    ('developer.production_access.approved', 'developer', 'production_access', 'approved',
     'A production access request was approved.', 'SECURITY', 1,
     '{"type":"object","required":["id","status","environmentId"]}', 'ACTIVE'),
    ('developer.production_access.rejected', 'developer', 'production_access', 'rejected',
     'A production access request was rejected.', 'SECURITY', 1,
     '{"type":"object","required":["id","status","environmentId"]}', 'ACTIVE'),
    ('developer.production_access.activated', 'developer', 'production_access', 'activated',
     'An approved production access grant was activated.', 'SECURITY', 1,
     '{"type":"object","required":["id","status","environmentId"]}', 'ACTIVE'),
    ('developer.production_access.suspended', 'developer', 'production_access', 'suspended',
     'A production access grant was suspended.', 'SECURITY', 1,
     '{"type":"object","required":["id","status","environmentId"]}', 'ACTIVE'),
    ('developer.production_access.reactivated', 'developer', 'production_access', 'reactivated',
     'A suspended production access grant was reactivated.', 'SECURITY', 1,
     '{"type":"object","required":["id","status","environmentId"]}', 'ACTIVE'),
    ('developer.production_access.revoked', 'developer', 'production_access', 'revoked',
     'A production access grant was permanently revoked.', 'SECURITY', 1,
     '{"type":"object","required":["id","status","environmentId"]}', 'ACTIVE'),
    ('developer.production_access.cancelled', 'developer', 'production_access', 'cancelled',
     'A production access request was cancelled by its requester.', 'SECURITY', 1,
     '{"type":"object","required":["id","status","environmentId"]}', 'ACTIVE')
on conflict (name) do nothing;
